INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06883","STANDARD","WESTON","CT","PRIMARY","41.22","-73.37","NA-US-CT-WESTON",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06875","PO BOX","REDDING CENTER","CT","PRIMARY","41.3","-73.38","NA-US-CT-REDDING CENTER",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06876","PO BOX","REDDING RIDGE","CT","PRIMARY","41.3","-73.38","NA-US-CT-REDDING RIDGE",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06896","STANDARD","REDDING","CT","PRIMARY","41.3","-73.38","NA-US-CT-REDDING",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06611","STANDARD","TRUMBULL","CT","PRIMARY","41.25","-73.2","NA-US-CT-TRUMBULL",FALSE);

INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("07444","STANDARD","POMPTON PLAINS","NJ","PRIMARY","40.96","-74.3","NA-US-NJ-POMPTON PLAINS",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("07035","STANDARD","LINCOLN PARK","NJ","PRIMARY","40.92","-74.3","NA-US-NJ-LINCOLN PARK",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("07477","UNIQUE","WAYNE","NJ","PRIMARY","40.92","-74.27","NA-US-NJ-WAYNE",TRUE);

INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92809","STANDARD","ANAHEIM","CA","PRIMARY","33.86","-117.74","NA-US-CA-ANAHEIM",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92808","STANDARD","ANAHEIM","CA","PRIMARY","33.84","-117.73","NA-US-CA-ANAHEIM",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92886","STANDARD","YORBA LINDA","CA","PRIMARY","33.89","-117.78","NA-US-CA-YORBA LINDA",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("91709","STANDARD","CHINO HILLS","CA","PRIMARY","33.94","-117.72","NA-US-CA-CHINO HILLS",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92807","STANDARD","ANAHEIM","CA","PRIMARY","33.85","-117.79","NA-US-CA-ANAHEIM",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92817","PO BOX","ANAHEIM","CA","PRIMARY","33.85","-117.79","NA-US-CA-ANAHEIM",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92823","STANDARD","BREA","CA","PRIMARY","33.92","-117.8","NA-US-CA-BREA",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92885","PO BOX","YORBA LINDA","CA","PRIMARY","33.89","-117.82","NA-US-CA-YORBA LINDA",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92862","STANDARD","ORANGE","CA","PRIMARY","33.79","-117.71","NA-US-CA-ORANGE",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92867","STANDARD","ORANGE","CA","PRIMARY","33.81","-117.79","NA-US-CA-ORANGE",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92880","STANDARD","CORONA","CA","PRIMARY","33.9","-117.61","NA-US-CA-CORONA",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92811","PO BOX","ATWOOD","CA","PRIMARY","33.86","-117.83","NA-US-CA-ATWOOD",FALSE);
INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92859","PO BOX","ORANGE","CA","PRIMARY","33.8","-117.78","NA-US-CA-ORANGE",FALSE);
